# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_param synth.incrementalSynthesisCache C:/Users/andy.zhang/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-6908-laba01/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xcvu9p-flga2104-2L-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vcu118:part0:2.0 [current_project]
set_property ip_output_repo c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_arch_description.svh
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/fpga-sdk-prj-master/arty/scr1/src/scr1_arch_custom.svh
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_arch_types.svh
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_ipic.svh
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_brkm.svh
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_csr.svh
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_memif.svh
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_tapc.svh
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_dbgc.svh
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_ahb.svh
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_riscv_isa_decoding.svh
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_search_ms1.svh
}
set_property file_type "Verilog Header" [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_arch_description.svh]
set_property file_type "Verilog Header" [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/fpga-sdk-prj-master/arty/scr1/src/scr1_arch_custom.svh]
set_property file_type "Verilog Header" [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_arch_types.svh]
set_property file_type "Verilog Header" [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_ipic.svh]
set_property file_type "Verilog Header" [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_brkm.svh]
set_property file_type "Verilog Header" [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_csr.svh]
set_property file_type "Verilog Header" [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_memif.svh]
set_property file_type "Verilog Header" [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_tapc.svh]
set_property file_type "Verilog Header" [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_dbgc.svh]
set_property file_type "Verilog Header" [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_ahb.svh]
set_property file_type "Verilog Header" [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_riscv_isa_decoding.svh]
set_property file_type "Verilog Header" [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/includes/scr1_search_ms1.svh]
read_verilog -library xil_defaultlib -sv {
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/pipeline/scr1_brkm_matcher.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/core/scr1_core_top.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/core/scr1_dbgc.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/top/scr1_dmem_ahb.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/top/scr1_dmem_router.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/top/scr1_dp_memory.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/top/scr1_imem_ahb.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/top/scr1_imem_router.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/pipeline/scr1_ipic.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/pipeline/scr1_pipe_brkm.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/pipeline/scr1_pipe_csr.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/pipeline/scr1_pipe_dbga.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/pipeline/scr1_pipe_exu.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/pipeline/scr1_pipe_ialu.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/pipeline/scr1_pipe_idu.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/pipeline/scr1_pipe_ifu.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/pipeline/scr1_pipe_lsu.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/pipeline/scr1_pipe_mprf.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/pipeline/scr1_pipe_top.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/core/scr1_sync_rstn.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/core/scr1_tapc.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/core/scr1_tapc_data_reg.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/core/scr1_tapc_shift_reg.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/core/scr1_tapc_synchronizer.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/top/scr1_tcm.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/top/scr1_timer.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/top/scr1_top_ahb.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/fpga-sdk-prj-master/arty/scr1/src/arty_scr1.sv
  C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/imports/syntacore/scr1-master/src/core/scr1_clk_ctrl.sv
}
add_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_ahblite_axi_bridge_0_0/system_ahblite_axi_bridge_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_ahblite_axi_bridge_1_0/system_ahblite_axi_bridge_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_0/system_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_jtag_axi_0_0/constraints/jtag_axi.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_jtag_axi_0_0/constraints/system_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_jtag_axi_0_0/constraints/system_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_jtag_axi_0_0/system_jtag_axi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/system/system_ooc.xdc]

add_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/sys_pll/sys_pll.bd
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/sys_pll/ip/sys_pll_clk_wiz_0_0/sys_pll_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/sys_pll/ip/sys_pll_clk_wiz_0_0/sys_pll_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/sys_pll/ip/sys_pll_clk_wiz_0_0/sys_pll_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/sources_1/bd/sys_pll/sys_pll_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/constrs_1/imports/constrs_u/arty_scr1_physical.xdc
set_property used_in_implementation false [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/constrs_1/imports/constrs_u/arty_scr1_physical.xdc]

read_xdc C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/constrs_1/imports/constrs_u/arty_scr1_synth.xdc
set_property used_in_implementation false [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/constrs_1/imports/constrs_u/arty_scr1_synth.xdc]

read_xdc C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/constrs_1/imports/constrs_u/arty_scr1_timing.xdc
set_property used_in_implementation false [get_files C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/constrs_1/imports/constrs_u/arty_scr1_timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top arty_scr1_top -part xcvu9p-flga2104-2L-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef arty_scr1_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file arty_scr1_top_utilization_synth.rpt -pb arty_scr1_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
