set_property SRC_FILE_INFO {cfile:C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/constrs_1/imports/constrs_u/arty_scr1_physical.xdc rfile:../../../project_1.srcs/constrs_1/imports/constrs_u/arty_scr1_physical.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/constrs_1/imports/constrs_u/arty_scr1_synth.xdc rfile:../../../project_1.srcs/constrs_1/imports/constrs_u/arty_scr1_synth.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/andy.zhang/work/fpga_proj/syntacore/project_1/project_1.srcs/constrs_1/imports/constrs_u/arty_scr1_timing.xdc rfile:../../../project_1.srcs/constrs_1/imports/constrs_u/arty_scr1_timing.xdc id:3} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G32 IOSTANDARD DIFF_SSTL12} [get_ports clk_in_n]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H32 IOSTANDARD DIFF_SSTL12} [get_ports clk_in_p]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS12} [get_ports RESETn]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L31 IOSTANDARD LVCMOS18} [get_ports {JD[0]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M31 IOSTANDARD LVCMOS18} [get_ports {JD[1]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R29 IOSTANDARD LVCMOS18} [get_ports {JD[6]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N28 IOSTANDARD LVCMOS18} [get_ports {JD[4]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M30 IOSTANDARD LVCMOS18} [get_ports {JD[5]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N30 IOSTANDARD LVCMOS18} [get_ports {JD[3]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P30 IOSTANDARD LVCMOS18} [get_ports {JD[7]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P29 IOSTANDARD LVCMOS18} [get_ports {JD[2]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {JD_IBUF[3]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AY14  IOSTANDARD LVCMOS18} [get_ports FTDI_RXD]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AY15  IOSTANDARD LVCMOS18} [get_ports FTDI_TXD]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G32 IOSTANDARD DIFF_SSTL12} [get_ports clk_in_n]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H32 IOSTANDARD DIFF_SSTL12} [get_ports clk_in_p]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -name SYS_CLK -period 20.00 [get_pins i_sys_pll/clk_wiz_0/inst/plle4_adv_inst/CLKOUT0]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks JTAG_TCK] -to [get_clocks SYS_CLK]
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks JTAG_TCK_VIRT] -to [get_clocks SYS_CLK]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks SYS_CLK] -to [get_clocks JTAG_TCK]
